import { createRng } from '../generation/rng';
import type { PlanetEcologyState, SpeciesStatus } from './types';
export interface EcologyCycleResult { ecology: PlanetEcologyState; event?: { kind: 'ecology' | 'disaster'; title: string; summary: string; severity: number; visibility: 'public' | 'local' | 'hidden'; tags: string[]; data?: Record<string, string | number | boolean> }; }
const clamp = (value: number, min = 0, max = 100) => Math.max(min, Math.min(max, value));
const statusFor = (abundance: number): SpeciesStatus => abundance <= 0 ? 'extinct' : abundance < 12 ? 'threatened' : abundance < 35 ? 'declining' : abundance > 76 ? 'thriving' : 'stable';
export function simulateEcologyCycle(input: PlanetEcologyState, seedKey: string, dueHour: number): EcologyCycleResult {
  const rng = createRng(`${seedKey}:${dueHour}:${input.cycle}`); const ecology = structuredClone(input); const previousBiomass = ecology.biomass; const previousBiodiversity = ecology.biodiversity; const previouslyExtinct = new Set(ecology.extinctSpeciesIds);
  ecology.climateStability = clamp(ecology.climateStability + rng.int(-4, 4) - Math.round(ecology.contamination / 35));
  for (const pathogen of ecology.pathogens) { if (!pathogen.active && rng.chance(Math.min(.32, pathogen.spread / 500 + ecology.contamination / 700))) pathogen.active = true; else if (pathogen.active && rng.chance(.18 + ecology.resilience / 500)) pathogen.active = false; }
  const abundance = new Map(ecology.species.map(e => [e.id, e.abundance]));
  for (const species of ecology.species) { if (species.status === 'extinct') continue; const prey = species.preyIds.length ? species.preyIds.reduce((sum,id)=>sum+(abundance.get(id)??0),0)/species.preyIds.length : ecology.biomass; const predators = species.predatorIds.reduce((sum,id)=>sum+(abundance.get(id)??0),0)/Math.max(1,species.predatorIds.length); const disease = ecology.pathogens.filter(p=>p.active&&p.hostSpeciesIds.includes(species.id)).reduce((sum,p)=>sum+p.virulence*p.lethality/160,0); const climate = Math.max(0,48-ecology.climateStability)/8; const delta = Math.round((prey-45)/13-predators/24-disease/8-climate+(species.resilience-50)/18+rng.int(-5,5)); species.abundance=clamp(species.abundance+delta); species.status=statusFor(species.abundance); if(species.status==='extinct'&&!ecology.extinctSpeciesIds.includes(species.id)) ecology.extinctSpeciesIds.push(species.id); }
  const living = ecology.species.filter(e=>e.status!=='extinct'); const producers=living.filter(e=>e.trophicLevel==='producer'); const producerAbundance=producers.reduce((s,e)=>s+e.abundance,0)/Math.max(1,producers.length); const activePathogens=ecology.pathogens.filter(p=>p.active);
  ecology.biomass=clamp(ecology.biomass+Math.round((producerAbundance-ecology.biomass)/8)+rng.int(-3,4)-Math.round(ecology.contamination/45)); ecology.biodiversity=clamp(living.length*4+ecology.biomes.length*5-ecology.extinctSpeciesIds.length*2); ecology.resilience=clamp((ecology.climateStability+ecology.biodiversity+ecology.biomass)/3-activePathogens.length*2); ecology.resources={ biomass:clamp(ecology.resources.biomass+Math.round((ecology.biomass-ecology.resources.biomass)/6)), medicinal:clamp(ecology.resources.medicinal+Math.round((ecology.biodiversity-50)/18)-activePathogens.length), organics:clamp(ecology.resources.organics+Math.round((ecology.biomass-50)/15)), rareCompounds:clamp(ecology.resources.rareCompounds+rng.int(-2,2)) }; ecology.cycle++; ecology.lastUpdatedHour=dueHour;
  const newExtinctions=ecology.extinctSpeciesIds.filter(id=>!previouslyExtinct.has(id)); const outbreak=ecology.pathogens.find(p=>p.active&&p.lethality>=35&&p.spread>=35); const biomassDelta=ecology.biomass-previousBiomass; const biodiversityDelta=ecology.biodiversity-previousBiodiversity;
  if(newExtinctions.length){const names=newExtinctions.map(id=>ecology.species.find(e=>e.id===id)?.name??id).slice(0,3);return{ecology,event:{kind:'ecology',title:'Локальное вымирание',summary:`Исчезли виды: ${names.join(', ')}. Пищевая сеть перестраивается.`,severity:Math.min(9,5+newExtinctions.length),visibility:'local',tags:['ecology','extinction'],data:{extinctCount:newExtinctions.length,biodiversityDelta}}};}
  if(outbreak&&rng.chance(.35))return{ecology,event:{kind:'disaster',title:`Вспышка: ${outbreak.name}`,summary:`Патоген распространяется среди ${outbreak.hostSpeciesIds.length} групп организмов. Биомасса ${ecology.biomass}/100.`,severity:Math.max(4,Math.round((outbreak.virulence+outbreak.lethality)/22)),visibility:'local',tags:['ecology','disease'],data:{pathogenId:outbreak.id,virulence:outbreak.virulence,lethality:outbreak.lethality}}};
  if(ecology.biomass<=22||ecology.biodiversity<=24)return{ecology,event:{kind:'disaster',title:'Экосистема входит в коллапс',summary:`Биомасса ${ecology.biomass}/100, биоразнообразие ${ecology.biodiversity}/100. Несколько пищевых цепей разрушены.`,severity:8,visibility:'local',tags:['ecology','collapse'],data:{biomass:ecology.biomass,biodiversity:ecology.biodiversity}}};
  if(biomassDelta>=9&&ecology.biomass>=72)return{ecology,event:{kind:'ecology',title:'Массовое биологическое цветение',summary:`Продуценты резко увеличили биомассу до ${ecology.biomass}/100. Ресурсы и риски заражения растут.`,severity:4,visibility:'local',tags:['ecology','bloom'],data:{biomassDelta}}};
  if(previousBiomass<35&&ecology.biomass>=42&&biodiversityDelta>0)return{ecology,event:{kind:'ecology',title:'Экологическое восстановление',summary:`Биомасса восстановилась до ${ecology.biomass}/100, биоразнообразие до ${ecology.biodiversity}/100.`,severity:3,visibility:'local',tags:['ecology','recovery']}};
  return { ecology };
}
