import { useEffect, useRef, useState } from 'react';
import { GalaxyCanvas } from './components/GalaxyCanvas';
import { ExpeditionModal } from './components/ExpeditionModal';
import { ShipCombatModal } from './components/ShipCombatModal';
import { SystemMap } from './components/SystemMap';
import { roleLabel } from './crew/generateCrew';
import type { GenerationProgress } from './generation/generateGalaxy';
import { generateGalaxyInWorker } from './generation/generateInWorker';
import type { Artifact, Contract, GalaxySettings, Planet, PointOfInterest } from './game/types';
import { useGameStore } from './game/store';
import { exportSnapshot, readSnapshotFile } from './persistence/db';
import { forceApplicationUpdate } from './runtime/update';
import { APP_CODENAME, APP_VERSION, BUILD_TIME, SAVE_SCHEMA_VERSION } from './version';
import { generateMarket } from './world/livingGalaxy';
import './styles/app.css';

const defaultSettings: GalaxySettings = {
  seed: 'VOID-CHRONICLES-004', systemCount: 300, historyYears: 2_000_000,
  civilizationCount: 12, lifeFrequency: 0.34, anomalyFrequency: 0.035, difficulty: 'standard'
};

const formatYear = (year: number) => year < 0 ? `${Math.abs(year).toLocaleString('ru-RU')} лет до старта` : `Год ${year}`;
const VersionBadge = () => <span className="version-badge">v{APP_VERSION}</span>;
const contractStatusLabel = (contract: Contract) => contract.status === 'available' ? 'доступен' : contract.status === 'active' ? 'активен' : contract.status === 'completed' ? 'выполнен' : contract.status === 'expired' ? 'просрочен' : 'провален';

function MainMenu() {
  const store = useGameStore();
  const [settings, setSettings] = useState(defaultSettings);
  const [progress, setProgress] = useState<GenerationProgress | null>(null);
  const fileRef = useRef<HTMLInputElement | null>(null);
  const create = async () => {
    if (store.generationActive || store.busyAction) return;
    store.setGenerationActive(true);
    setProgress({ stage: 'start', progress: 0.01, message: 'Инициализация генератора' });
    try { await store.startGame(await generateGalaxyInWorker(settings, setProgress)); }
    catch (error) { setProgress({ stage: 'error', progress: 0, message: error instanceof Error ? error.message : 'Ошибка генерации' }); }
    finally { store.setGenerationActive(false); }
  };
  const importSave = async (file?: File) => {
    if (!file) return;
    try { await store.restoreSnapshot(await readSnapshotFile(file)); }
    catch (error) { alert(error instanceof Error ? error.message : 'Не удалось импортировать сохранение'); }
  };
  return <main className="menu-screen"><div className="menu-stars"/><section className="menu-panel">
    <div className="menu-version"><VersionBadge/><span>{APP_CODENAME}</span></div>
    <span className="eyebrow">PROCEDURAL SPACE ROGUELIKE</span><h1>VOID<br/>CHRONICLES</h1>
    <p className="menu-subtitle">Галактика живёт сама. Порты дают работу, фракции помнят поступки, а зачищенные локации не восстанавливаются после выхода.</p>
    {store.recoveryNotice && <div className="recovery-notice"><b>Система сохранений</b><p>{store.recoveryNotice}</p><button onClick={store.dismissRecoveryNotice}>Закрыть</button></div>}
    {store.saveError && <div className="save-error"><b>Сейв не загружен</b><p>{store.saveError}</p><div className="menu-actions"><button onClick={store.dismissSaveError}>Скрыть</button><button className="danger-button" onClick={() => void store.clearGame()}>Удалить повреждённый сейв</button></div></div>}
    {progress ? <div className="generation-panel"><div className="generation-line"><span>{progress.stage.toUpperCase()}</span><strong>{Math.round(progress.progress * 100)}%</strong></div><div className="progress-track"><i style={{width:`${progress.progress*100}%`}}/></div><p>{progress.message}</p>{progress.stage==='error'&&<button onClick={()=>setProgress(null)}>Вернуться</button>}</div> : <>
      <div className="seed-row"><label>SEED<input value={settings.seed} onChange={(e)=>setSettings({...settings,seed:e.target.value||'VOID'})}/></label><button onClick={()=>setSettings({...settings,seed:`VOID-${Math.random().toString(36).slice(2,10).toUpperCase()}`})}>Случайный</button></div>
      <div className="settings-grid"><label>Системы<input type="number" min="20" max="1500" value={settings.systemCount} onChange={(e)=>setSettings({...settings,systemCount:Number(e.target.value)})}/></label><label>История<select value={settings.historyYears} onChange={(e)=>setSettings({...settings,historyYears:Number(e.target.value)})}><option value={100000}>100 000</option><option value={2000000}>2 000 000</option><option value={10000000}>10 000 000</option></select></label><label>Цивилизации<input type="number" min="2" max="80" value={settings.civilizationCount} onChange={(e)=>setSettings({...settings,civilizationCount:Number(e.target.value)})}/></label><label>Сложность<select value={settings.difficulty} onChange={(e)=>setSettings({...settings,difficulty:e.target.value as GalaxySettings['difficulty']})}><option value="explorer">Исследователь</option><option value="standard">Стандарт</option><option value="brutal">Жестокая</option></select></label></div>
      <div className="menu-actions"><button className="primary-button large" disabled={store.generationActive||Boolean(store.busyAction)} onClick={create}>{store.generationActive?'Генерация…':'Создать галактику'}</button>{store.saveAvailable&&<button onClick={()=>void store.resumeGame()}>Продолжить ironman</button>}<button onClick={()=>fileRef.current?.click()}>Импорт сохранения</button><button onClick={()=>store.setScreen('settings')}>Настройки</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={(e)=>void importSave(e.target.files?.[0])}/></div>
    </>}
    <footer>v{APP_VERSION} · {APP_CODENAME}</footer>
  </section></main>;
}

function TopBar() {
  const store = useGameStore();
  if (!store.captain || !store.ship) return null;
  const nav = [['command','Мостик'],['galaxy','Галактика'],['system','Система'],['contracts','Контракты'],['factions','Фракции'],['crew','Экипаж'],['ship','Корабль'],['archive','Архив'],['settings','Настройки']] as const;
  const mobile = [['command','Мостик'],['galaxy','Карта'],['system','Система'],['contracts','Работа'],['crew','Люди'],['ship','Корабль']] as const;
  return <><header className="topbar"><button className="brand-button" onClick={()=>store.setScreen('command')}><b>VOID</b><span>CHRONICLES</span><VersionBadge/></button><nav>{nav.map(([id,label])=><button key={id} className={store.screen===id?'active':''} onClick={()=>store.setScreen(id)}>{label}</button>)}</nav><div className="top-stats"><span className={`save-state save-${store.saveStatus}`}>{store.saveStatus==='saving'||store.saveStatus==='pending'?'СОХРАНЕНИЕ…':store.saveStatus==='error'?'ОШИБКА':'IRONMAN'}</span><span>{formatYear(store.gameYear)}</span><span>₡ {store.captain.credits}</span><span>ТОПЛИВО {store.ship.fuel}</span></div></header><nav className="mobile-bottom-nav">{mobile.map(([id,label])=><button key={id} className={store.screen===id?'active':''} onClick={()=>store.setScreen(id)}>{label}</button>)}</nav></>;
}

function CommandDeckScreen() {
  const store = useGameStore();
  const current = store.galaxy?.systems.find((system)=>system.id===store.currentSystemId);
  if (!current || !store.ship || !store.captain) return null;
  const localHubs = store.hubs.filter((hub)=>hub.systemId===current.id);
  const localFaction = store.factions.find((faction)=>faction.id===current.factionId);
  const active = store.contracts.filter((contract)=>contract.status==='active');
  return <div className="game-shell"><TopBar/><main className="command-deck">
    <section className="command-hero"><div><span className="eyebrow">КОМАНДНЫЙ МОСТИК · {current.region.toUpperCase()}</span><h1>{current.name}</h1><p>{localFaction ? `${localFaction.name} · отношение: ${localFaction.disposition}` : 'Нейтральное пространство без единого контроля.'}</p><div className="hero-actions"><button className="primary-button" onClick={()=>store.setScreen('system')}>Открыть систему</button><button onClick={()=>store.setScreen('contracts')}>Доска контрактов</button>{localHubs[0]&&<button onClick={()=>void store.dockAtHub(localHubs[0].id)}>Стыковка: {localHubs[0].name}</button>}</div></div><div className="command-ship"><div className="ship-silhouette compact"><div className="ship-core"/><div className="ship-wing left"/><div className="ship-wing right"/></div></div></section>
    <section className="command-grid">
      <article className="command-card"><span className="eyebrow">КОРАБЛЬ</span><h2>{store.ship.name}</h2><div className="stat-row"><span>Корпус</span><b>{store.ship.hull}/{store.ship.maxHull}</b></div><div className="stat-row"><span>Топливо</span><b>{store.ship.fuel}/{store.ship.maxFuel}</b></div><div className="stat-row"><span>Груз</span><b>{store.ship.cargo.length}/{store.ship.cargoCapacity}</b></div></article>
      <article className="command-card"><span className="eyebrow">ХАБЫ И ПОСЕЛЕНИЯ</span><h2>{localHubs.length}</h2>{localHubs.length?localHubs.map((hub)=><div className="compact-row" key={hub.id}><div><b>{hub.name}</b><small>{hub.kind} · {hub.safety}</small></div><button onClick={()=>void store.dockAtHub(hub.id)}>Стыковка</button></div>):<p>В системе нет известного гражданского порта.</p>}</article>
      <article className="command-card"><span className="eyebrow">АКТИВНЫЕ КОНТРАКТЫ</span><h2>{active.length}</h2>{active.slice(0,3).map((contract)=><div className="compact-row" key={contract.id}><div><b>{contract.title}</b><small>{contract.progress}/{contract.requiredProgress} · до {contract.deadlineYear}</small></div></div>)}<button onClick={()=>store.setScreen('contracts')}>Все контракты</button></article>
      <article className="command-card"><span className="eyebrow">ЭКИПАЖ</span><h2>{store.crew.length + 1}</h2><p>Капитан и {store.crew.length} напарников. Жалование: ₡{store.crew.reduce((sum,member)=>sum+member.salary,0)}.</p><button onClick={()=>store.setScreen('crew')}>Управление экипажем</button></article>
      <article className="command-card command-log"><span className="eyebrow">НОВОСТИ СЕТИ</span>{store.news.slice(0,5).map((item)=><div key={item.id}><b>{item.headline}</b><p>{item.text}</p><small>{formatYear(item.year)} · достоверность {item.reliability}%</small></div>)}</article>
      <article className="command-card alerts-card"><span className="eyebrow">ОБСТАНОВКА</span><p>{localFaction?.disposition==='friendly'?'Местная власть дружественна. Гражданские контакты не атакуют без причины.':localFaction?.disposition==='hostile'?'Фракция враждебна. Стыковка запрещена, перехват вероятен.':'Контакты оценивают корабль. Ответ на запрос связи снижает риск конфликта.'}</p>{store.ship.cargo.some((item)=>item.illegal)&&<p className="warning-text">В трюме находится запрещённый груз. В законных портах возможен досмотр.</p>}</article>
    </section>
  </main></div>;
}

function GalaxyScreen() {
  const store = useGameStore();
  const [notice,setNotice]=useState('');
  const [combat,setCombat]=useState(false);
  if(!store.galaxy||!store.ship||!store.currentSystemId)return null;
  const current=store.galaxy.systems.find((system)=>system.id===store.currentSystemId);
  const selected=store.galaxy.systems.find((system)=>system.id===store.selectedSystemId)??current;
  if(!current||!selected)return null;
  const jumpDistance=Math.hypot(selected.coordinates.x-current.coordinates.x,selected.coordinates.y-current.coordinates.y);
  const canTravel=selected.id!==current.id&&current.neighbors.includes(selected.id)&&jumpDistance<=store.ship.jumpRange;
  const faction=store.factions.find((entry)=>entry.id===selected.factionId);
  return <div className="game-shell"><TopBar/><main className="galaxy-screen-separated"><section className="galaxy-map-full"><GalaxyCanvas systems={store.galaxy.systems} currentSystemId={current.id} selectedSystemId={selected.id} jumpRange={store.ship.jumpRange} onSelect={store.selectSystem}/>{notice&&<button className="notice" onClick={()=>setNotice('')}>{notice}</button>}</section><aside className="galaxy-route-panel"><span className="eyebrow">МЕЖЗВЁЗДНАЯ НАВИГАЦИЯ</span><h1>{selected.name}</h1><p>{selected.region} · угроза {selected.danger}</p>{faction&&<div className={`faction-strip disposition-${faction.disposition}`}><b>{faction.name}</b><span>{faction.disposition} · репутация {faction.reputation}</span></div>}<div className="stat-row"><span>Дистанция</span><b>{Math.round(jumpDistance)}</b></div><div className="stat-row"><span>Хабы</span><b>{store.hubs.filter((hub)=>hub.systemId===selected.id).length}</b></div>{selected.id===current.id?<button className="primary-button" onClick={()=>store.setScreen('system')}>Открыть карту системы</button>:<button className="primary-button" disabled={!canTravel||Boolean(store.busyAction)} onClick={async()=>{const result=await store.travelTo(selected.id);setNotice(result.message);if(result.encounter==='shipCombat')setCombat(true);}}>Прыжок · {Math.max(7,Math.ceil(jumpDistance/14))} топлива</button>}{!current.neighbors.includes(selected.id)&&selected.id!==current.id&&<p className="warning-text">Нет прямого маршрута.</p>}</aside>{combat&&<ShipCombatModal playerHull={store.ship.hull} onDamage={store.damageShip} onVictory={async()=>{await store.earnCredits(620,'Победа в корабельном бою');setCombat(false);}} onEscape={()=>setCombat(false)} onDefeat={()=>setCombat(false)}/>}</main></div>;
}

function artifactForPoint(point: PointOfInterest, artifacts: Artifact[]) { return artifacts.find((entry)=>entry.civilizationId===point.civilizationId&&!entry.discovered)??artifacts.find((entry)=>!entry.discovered); }

function SystemScreen() {
  const store=useGameStore();
  const [planetId,setPlanetId]=useState<string|null>(null);
  const [point,setPoint]=useState<PointOfInterest|null>(null);
  const [notice,setNotice]=useState('');
  if(!store.galaxy||!store.currentSystemId)return null;
  const system=store.galaxy.systems.find((entry)=>entry.id===store.currentSystemId);
  if(!system)return null;
  const planet=system.planets.find((entry)=>entry.id===planetId)??null;
  const planetPoints=planet?store.pointsOfInterest.filter((entry)=>entry.planetId===planet.id):[];
  const report=planet?store.scanReports.find((entry)=>entry.planetId===planet.id):undefined;
  const localHubs=store.hubs.filter((hub)=>hub.systemId===system.id);
  const locationState=point?store.locationStates.find((entry)=>entry.pointOfInterestId===point.id):undefined;
  return <div className="game-shell"><TopBar/><main className="system-screen-separated"><section className="system-map-shell"><header><div><span className="eyebrow">ЛОКАЛЬНАЯ НАВИГАЦИЯ</span><h1>{system.name}</h1><p>{system.starClass} · {system.planets.length} планет · {localHubs.length} гражданских узлов</p></div><button className="primary-button" disabled={Boolean(store.busyAction)} onClick={()=>void store.scanSystem(system.id)}>{system.scanned?'Обновить системный скан':'Системный скан'}</button></header><SystemMap system={system} selectedPlanetId={planetId} pointsOfInterest={store.pointsOfInterest.filter((entry)=>entry.systemId===system.id)} onSelectPlanet={(entry)=>setPlanetId(entry.id)}/><section className="local-hubs"><h3>Хабы и поселения</h3>{localHubs.length?localHubs.map((hub)=><article key={hub.id}><div><span className="eyebrow">{hub.kind} · {hub.safety}</span><b>{hub.name}</b><p>{hub.description}</p></div><button onClick={async()=>setNotice((await store.dockAtHub(hub.id)).message)}>Стыковка</button></article>):<p className="empty-state">Гражданских узлов не обнаружено.</p>}</section></section><aside className="system-object-panel">{notice&&<p className="notice-inline">{notice}</p>}{planet?<><div className={`planet-orb planet-${planet.type}`}><span/></div><h2>{planet.scanLevel?planet.name:'НЕИЗВЕСТНЫЙ ОБЪЕКТ'}</h2><p>{planet.type} · пригодность {planet.habitability}% · угроза {planet.danger}</p><button disabled={!system.scanned||Boolean(store.busyAction)} onClick={async()=>setNotice((await store.detailedScanPlanet(planet.id)).message)}>Детальный скан</button>{report&&<article className="scan-report"><span>ДОСТОВЕРНОСТЬ {Math.round(report.confidence)}%</span><p>{report.summary}</p></article>}<div className="poi-list">{planetPoints.length?planetPoints.map((entry)=>{const state=store.locationStates.find((location)=>location.pointOfInterestId===entry.id);return <article className={`poi-card poi-${entry.status}`} key={entry.id}><div><span className="eyebrow">{entry.type} · {entry.danger} · {entry.status}</span><h3>{entry.name}</h3><p>{entry.publicSummary}</p>{state&&<small>Визитов: {state.visitCount} · врагов осталось: {state.enemyStates.filter((enemy)=>enemy.health>0).length} · данные забраны: {state.collectedEvidenceKeys.length}</small>}</div>{planet.type!=='gas'&&<button onClick={()=>setPoint(entry)}>Высадка</button>}</article>}):<p className="empty-state">Точки интереса не определены.</p>}</div></>:<p>Выберите планету.</p>}</aside>{point&&planet&&<ExpeditionModal seed={`${store.galaxy.seed}:${planet.id}`} planet={planet} point={point} artifact={artifactForPoint(point,store.galaxy.artifacts)} crew={store.crew} locationState={locationState} onClose={()=>setPoint(null)} onComplete={store.completeExpedition}/>}</main></div>;
}

function HubScreen() {
  const store=useGameStore();
  const hub=store.hubs.find((entry)=>entry.id===store.currentHubId);
  const [message,setMessage]=useState('');
  if(!hub)return <div className="game-shell"><TopBar/><main className="hub-screen"><p>Корабль не пристыкован.</p><button onClick={()=>store.setScreen('system')}>Вернуться в систему</button></main></div>;
  const faction=store.factions.find((entry)=>entry.id===hub.factionId);
  const market=generateMarket(hub,store.gameYear);
  const hubContracts=store.contracts.filter((contract)=>contract.issuerHubId===hub.id&&contract.status==='available');
  return <div className="game-shell"><TopBar/><main className="hub-screen"><header><div><span className="eyebrow">{hub.kind.toUpperCase()} · НАСЕЛЕНИЕ {hub.population.toLocaleString('ru-RU')}</span><h1>{hub.name}</h1><p>{hub.description}</p></div><button onClick={()=>void store.leaveHub()}>Отстыковаться</button></header>{message&&<p className="notice-inline">{message}</p>}<section className="hub-grid"><article><h2>Власть</h2><h3>{faction?.name}</h3><p>Отношение: <b>{faction?.disposition}</b> · репутация {faction?.reputation}</p><div className="tags">{faction?.laws.map((law)=><span key={law}>{law}</span>)}</div></article><article><h2>Услуги</h2><div className="tags">{hub.services.map((service)=><span key={service}>{service}</span>)}</div><button onClick={()=>store.setScreen('crew')}>Найм экипажа</button><button onClick={()=>store.setScreen('contracts')}>Контракты</button></article><article className="hub-market"><h2>Рынок</h2>{market.map((good)=><div className="market-row" key={good.id}><div><b>{good.name}</b><small>{good.category}{good.illegal?' · ЗАПРЕЩЕНО':''}</small></div><span>₡{good.price}</span><button onClick={async()=>setMessage((await store.buyMarketGood(hub.id,good)).message)}>Купить</button></div>)}</article><article><h2>Доска заданий</h2>{hubContracts.slice(0,5).map((contract)=><div className="contract-mini" key={contract.id}><b>{contract.title}</b><p>{contract.description}</p><button onClick={async()=>setMessage((await store.acceptContract(contract.id)).message)}>Принять · ₡{contract.reward}</button></div>)}<button onClick={()=>void store.refreshContracts()}>Обновить доску</button></article><article><h2>Продать груз</h2>{store.ship?.cargo.filter((item)=>!item.contractId).map((item)=><div className="market-row" key={item.id}><div><b>{item.name}</b><small>{item.illegal?'контрабанда':'товар'}</small></div><button onClick={()=>void store.sellCommodity(item.id,hub.id)}>Продать</button></div>)}</article></section></main></div>;
}

function ContractsScreen() {
  const store=useGameStore();
  const [filter,setFilter]=useState<'all'|'available'|'active'>('all');
  const visible=store.contracts.filter((contract)=>filter==='all'||contract.status===filter);
  return <div className="game-shell"><TopBar/><main className="contracts-screen"><header><div><span className="eyebrow">РАБОТА И ОБЯЗАТЕЛЬСТВА</span><h1>Контракты</h1></div><div className="tabs"><button onClick={()=>setFilter('all')}>Все</button><button onClick={()=>setFilter('available')}>Доступные</button><button onClick={()=>setFilter('active')}>Активные</button></div></header><section className="contract-grid">{visible.map((contract)=><article className={`contract-card status-${contract.status}`} key={contract.id}><span className="eyebrow">{contract.type} · {contractStatusLabel(contract)}</span><h2>{contract.title}</h2><p>{contract.description}</p><div className="stat-row"><span>Награда</span><b>₡{contract.reward}</b></div><div className="stat-row"><span>Срок</span><b>{contract.deadlineYear}</b></div><div className="stat-row"><span>Прогресс</span><b>{contract.progress}/{contract.requiredProgress}</b></div>{contract.illegal&&<p className="warning-text">Незаконный контракт. Возможны досмотр и конфискация.</p>}{contract.status==='available'&&<button className="primary-button" onClick={()=>void store.acceptContract(contract.id)}>Принять · аванс ₡{contract.advance}</button>}</article>)}</section></main></div>;
}

function FactionsScreen() {
  const store=useGameStore();
  return <div className="game-shell"><TopBar/><main className="factions-screen"><header><span className="eyebrow">ПОЛИТИЧЕСКАЯ КАРТА</span><h1>Фракции</h1><p>Они запоминают конкретные поступки. Репутация меняется не сама по себе.</p></header><section className="faction-grid">{store.factions.map((faction)=><article className={`faction-card disposition-${faction.disposition}`} key={faction.id}><span className="eyebrow">{faction.kind} · {faction.disposition}</span><h2>{faction.name}</h2><div className="stat-row"><span>Репутация</span><b>{faction.reputation}</b></div><div className="stat-row"><span>Военная сила</span><b>{faction.military}</b></div><div className="stat-row"><span>Исследования</span><b>{faction.research}</b></div><div className="tags">{faction.laws.map((law)=><span key={law}>{law}</span>)}</div><h3>Память</h3>{faction.memories.slice(0,4).map((memory)=><p key={memory.id}>{memory.text} <b>{memory.impact>0?'+':''}{memory.impact}</b></p>)}</article>)}</section></main></div>;
}

function CrewScreen() {
  const store=useGameStore();
  return <div className="game-shell"><TopBar/><main className="crew-screen"><header><div><span className="eyebrow">ЛЮДИ КОРАБЛЯ</span><h1>Экипаж</h1><p>Полноценные напарники редки. Максимум активного состава — четыре.</p></div><div><button disabled={Boolean(store.busyAction)} onClick={()=>void store.refreshCrewCandidates()}>Найти кандидатов · ₡40</button><button disabled={Boolean(store.busyAction)||store.crew.length===0} onClick={()=>void store.settlePayroll()}>Выплатить жалование</button></div></header><section className="crew-columns"><div><h2>На борту · {store.crew.length}/4</h2><div className="crew-grid">{store.crew.length?store.crew.map((member)=><article className="crew-card" key={member.id}><span className={`crew-status status-${member.status}`}>{member.status}</span><div className="crew-avatar">{member.name.slice(0,1)}</div><h3>{member.name}</h3><p>{member.species} · {member.culture}</p><b>{roleLabel(member.primaryRole)}{member.secondaryRole?` / ${roleLabel(member.secondaryRole)}`:''}</b><div className="stat-row"><span>Здоровье</span><b>{member.health}</b></div><div className="stat-row"><span>Мораль</span><b>{member.morale}</b></div><div className="stat-row"><span>Верность</span><b>{member.loyalty}</b></div><div className="tags">{member.traits.map((trait)=><span key={trait}>{trait}</span>)}</div><small>Зарплата: ₡{member.salary} · доля {member.sharePercent}%</small><button className="danger-button" onClick={()=>void store.dismissCrew(member.id)}>Расторгнуть контракт</button></article>):<p className="empty-state">Ты пока один. Кандидатов проще искать в хабах.</p>}</div></div><div><h2>Кандидаты</h2><div className="crew-grid">{store.crewCandidates.length?store.crewCandidates.map((candidate)=><article className="crew-card candidate" key={candidate.id}><div className="crew-avatar">{candidate.name.slice(0,1)}</div><h3>{candidate.name}</h3><p>{candidate.species} · {candidate.culture}</p><b>{roleLabel(candidate.primaryRole)} · уровень {candidate.level}</b><div className="tags">{candidate.traits.map((trait)=><span key={trait}>{trait}</span>)}</div><div className="stat-row"><span>Подписание</span><b>₡{candidate.signingCost}</b></div><button className="primary-button" disabled={store.crew.length>=4||(store.captain?.credits??0)<candidate.signingCost} onClick={()=>void store.hireCrew(candidate.id)}>Нанять</button></article>):<p className="empty-state">Список пуст.</p>}</div></div></section></main></div>;
}

function ArchiveScreen(){const {galaxy,discoveries,logs,evidence,hypotheses,pointsOfInterest,locationStates}=useGameStore();const[tab,setTab]=useState<'discoveries'|'evidence'|'hypotheses'|'locations'|'history'|'civilizations'>('discoveries');const[query,setQuery]=useState('');if(!galaxy)return null;const q=query.toLowerCase();return <div className="game-shell"><TopBar/><main className="archive-screen"><header><div><span className="eyebrow">ИССЛЕДОВАТЕЛЬСКИЙ АРХИВ</span><h1>Архив экспедиции</h1></div><input placeholder="Поиск" value={query} onChange={(e)=>setQuery(e.target.value)}/></header><nav className="tabs">{(['discoveries','evidence','hypotheses','locations','history','civilizations'] as const).map((id)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{id}</button>)}</nav><section className="archive-grid">{tab==='discoveries'&&discoveries.filter((x)=>`${x.name} ${x.description}`.toLowerCase().includes(q)).map((x)=><article key={x.id}><span>{x.kind} · {x.confidence}%</span><h3>{x.name}</h3><p>{x.description}</p></article>)}{tab==='evidence'&&evidence.filter((x)=>`${x.title} ${x.description}`.toLowerCase().includes(q)).map((x)=><article key={x.id}><span>{x.kind} · {x.reliability}%</span><h3>{x.title}</h3><p>{x.description}</p><small>{pointsOfInterest.find((p)=>p.id===x.pointOfInterestId)?.name}</small></article>)}{tab==='hypotheses'&&hypotheses.map((x)=><article key={x.id}><span>{x.status} · {x.confidence}%</span><h3>{x.title}</h3><p>{x.summary}</p></article>)}{tab==='locations'&&locationStates.map((state)=><article key={state.pointOfInterestId}><span>визитов {state.visitCount} · {state.lastOutcome}</span><h3>{pointsOfInterest.find((point)=>point.id===state.pointOfInterestId)?.name??state.pointOfInterestId}</h3><p>Врагов осталось: {state.enemyStates.filter((enemy)=>enemy.health>0).length}. Объектов использовано: {state.resolvedObjectIds.length}. Данных забрано: {state.collectedEvidenceKeys.length}.</p></article>)}{tab==='history'&&galaxy.history.slice(-120).reverse().map((x)=><article key={x.id}><span>{formatYear(x.year)}</span><h3>{x.title}</h3><p>{x.summary}</p></article>)}{tab==='civilizations'&&galaxy.civilizations.map((x)=><article key={x.id}><span>{x.status} · tech {x.techLevel}</span><h3>{x.name}</h3><p>{x.speciesName}. {x.ideology}.</p></article>)}</section><aside className="archive-summary"><b>Последние записи</b>{logs.slice(0,5).map((x)=><p key={x.id}>{x.title}</p>)}</aside></main></div>}

function ShipScreen(){const s=useGameStore();if(!s.ship||!s.captain)return null;const snap=s.getSnapshot();return <div className="game-shell"><TopBar/><main className="ship-screen"><section className="ship-hero"><span className="eyebrow">ЛИЧНЫЙ КОРАБЛЬ</span><h1>{s.ship.name}</h1><div className="ship-silhouette"><div className="ship-core"/><div className="ship-wing left"/><div className="ship-wing right"/></div><div className="ship-actions"><button onClick={()=>void s.repairShip()}>Ремонт</button><button onClick={()=>void s.refuelShip()}>Заправка</button>{snap&&<button onClick={()=>exportSnapshot(snap)}>Экспорт</button>}<button onClick={()=>void s.createBackup()}>Backup ({s.backupCount})</button><button className="danger-button" onClick={()=>void s.clearGame()}>Удалить ironman</button></div></section><section className="ship-data"><article><h2>Состояние</h2><div className="meter"><span>Корпус</span><strong>{s.ship.hull}</strong><i style={{width:`${s.ship.hull}%`}}/></div><div className="meter"><span>Топливо</span><strong>{s.ship.fuel}</strong><i style={{width:`${s.ship.fuel}%`}}/></div></article><article><h2>Модули</h2>{s.ship.modules.map((m)=><div className="module-row" key={m.id}><span>{m.slot}</span><div><b>{m.name}</b><p>{m.effect}</p></div></div>)}</article><article><h2>Капитан</h2><p>{s.captain.name} · уровень {s.captain.level}</p><p>Здоровье {s.captain.health}/{s.captain.maxHealth}</p></article><article><h2>Груз и анализ</h2>{s.ship.cargo.length===0?<p>Трюм пуст.</p>:s.ship.cargo.map((item)=>{const knowledge=item.artifactId?s.artifactKnowledge.find((entry)=>entry.artifactId===item.artifactId):undefined;return <div className="module-row cargo-analysis" key={item.id}><div><b>{item.name}</b><p>{item.illegal?'ЗАПРЕЩЁННЫЙ ГРУЗ · ':''}оценка ₡{item.value} · знания {knowledge?.level??0}/4</p>{item.artifactId&&<button disabled={(knowledge?.level??0)>=4} onClick={()=>void s.analyzeArtifact(item.artifactId!)}>Анализ ₡120</button>}{!item.contractId&&!item.commodityId&&<button onClick={()=>void s.sellCargo(item.id)}>Продать ₡{Math.round(item.value*.72)}</button>}</div></div>})}</article></section></main></div>}

function SettingsScreen(){const s=useGameStore();const[updating,setUpdating]=useState(false);const snap=s.getSnapshot();const update=async()=>{setUpdating(true);try{await forceApplicationUpdate();}catch(error){setUpdating(false);alert(error instanceof Error?error.message:'Ошибка обновления');}};return <div className="game-shell">{s.galaxy&&<TopBar/>}<main className="settings-screen"><header><div><span className="eyebrow">СИСТЕМА</span><h1>Настройки</h1></div>{!s.galaxy&&<button onClick={()=>s.setScreen('menu')}>Назад</button>}</header><section className="settings-cards"><article><h2>Версия</h2><div className="version-hero">v{APP_VERSION}</div><p>{APP_CODENAME}</p><div className="stat-row"><span>Схема сейва</span><b>v{SAVE_SCHEMA_VERSION}</b></div><div className="stat-row"><span>Сборка</span><b>{BUILD_TIME==='development'?'development':new Date(BUILD_TIME).toLocaleString('ru-RU')}</b></div></article><article><h2>Обновление PWA</h2><button className="primary-button" disabled={updating} onClick={()=>void update()}>{updating?'Обновление…':'Принудительно обновить игру'}</button><small>IndexedDB и ironman не удаляются.</small></article><article><h2>Ironman</h2>{snap&&<button onClick={()=>exportSnapshot(snap)}>Экспортировать</button>}<button onClick={()=>void s.createBackup()}>Создать backup</button></article></section></main></div>}

const BootScreen=()=> <main className="boot-screen"><div className="boot-mark">◆</div><span className="eyebrow">VOID CHRONICLES · v{APP_VERSION}</span><p>Проверка локального архива…</p></main>;

export default function App(){const screen=useGameStore((s)=>s.screen);const galaxy=useGameStore((s)=>s.galaxy);const hydration=useGameStore((s)=>s.hydrationStatus);const hydrate=useGameStore((s)=>s.hydrateFromStorage);useEffect(()=>{void hydrate();},[hydrate]);if(hydration==='idle'||hydration==='loading')return <BootScreen/>;if(screen==='settings')return <SettingsScreen/>;if(!galaxy||screen==='menu')return <MainMenu/>;if(screen==='command')return <CommandDeckScreen/>;if(screen==='galaxy')return <GalaxyScreen/>;if(screen==='system')return <SystemScreen/>;if(screen==='hub')return <HubScreen/>;if(screen==='contracts')return <ContractsScreen/>;if(screen==='factions')return <FactionsScreen/>;if(screen==='crew')return <CrewScreen/>;if(screen==='archive')return <ArchiveScreen/>;return <ShipScreen/>;}
